version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: quiniela_predictor
      POSTGRES_USER: quiniela_user
      POSTGRES_PASSWORD: quiniela_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  api:
    build: 
      context: .
      dockerfile: Dockerfile.api
    environment:
      - DATABASE_URL=postgresql://quiniela_user:quiniela_password@postgres:5432/quiniela_predictor
      - REDIS_URL=redis://redis:6379
      - API_FOOTBALL_KEY=${API_FOOTBALL_KEY}
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    ports:
      - "8501:8501"
    depends_on:
      - api
    environment:
      - API_BASE_URL=http://api:8000
    restart: unless-stopped

  celery:
    build:
      context: .
      dockerfile: Dockerfile.api
    command: celery -A backend.app.celery worker --loglevel=info
    environment:
      - DATABASE_URL=postgresql://quiniela_user:quiniela_password@postgres:5432/quiniela_predictor
      - REDIS_URL=redis://redis:6379
      - API_FOOTBALL_KEY=${API_FOOTBALL_KEY}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - postgres
      - redis
    volumes:
      - ./data:/app/data
    restart: unless-stopped

volumes:
  postgres_data: